### ISSUE TITLE
Left click not picking up Entities as intended

### ISSUE THREAD

**Issue by DragonAbuse** [EmpressValla/TheEmeraldLasso#15] opened 2023-02-16 19:17 UTC
Why

**Comment by LJSkinner** [comment] 2023-02-16 19:56
> Why

@DragonAbuse 

Hi Dragon. Could you let me know your game version and what mob you were trying to pick up with the lasso?

**Comment by LJSkinner** [comment] 2023-02-22 18:52
@DragonAbuse 

I've had other reports now of this issue. It seems that for whatever reason adding my mod to an existing world is causing this problem for some people. I'm going to leave this issue open for now, as I don't currently know whether this is a bug in how I've wrote the mod or if it's just Minecraft being weird. **If you're having similar issues and you've added this mod to an existing world, please do check if creating a new world fixes the problem first.**

The only other scenario I've encountered is if you update from a previous version. It's unlikely that there will be a new major version of this mod, but if you had updated from the older 1.0.3 version this can cause the same issue.

I am going to do some testing to see if it's reliably possible to reproduce this issue.

**Comment by LJSkinner** [comment] 2023-03-04 23:46
I have tested this a few times with existing worlds where lots of chunks have been loaded and at least some progress has been made and I have not been able to reproduce this. Adding the lasso after the fact worked fine in all cases. I still plan on testing on a world which has been played on for much longer but at this point it seems as though I can't easily reproduce this bug.

At this point, I am assuming this is a weird issue sometimes happening with Minecraft worlds. **Please check the above comment to see if that fixes your problem**. For now, I'm assigning this as "wontfix" since I can't currently see an obvious cause in source code. However, I will leave this issue open, so **if this bug occurs under different circumstances. Please leave a comment here.**

**Also, if anyone wants to take a poke around the source code and see if there's something I'm missing that may be causing this. Feel free, I would appreciate it.**

**Comment by LJSkinner** [comment] 2023-03-16 02:05
So I have now been able to reproduce a version of this. Most similarly compared to issue #20 by mayophobia. In this instance I had added the lasso to an existing world and it worked in the beginning but I did eventually have a point where I was forced to relog for the lasso to work.

Here is the fix I found for this issue (on servers):

1.) Create a single player world fresh and let the world load in
2.) Test the lasso in this environment to confirm that it is working
3.) Rejoin the server and re-test the lasso on the server

These steps seemed to fix this and the lasso now works 100% of the time.

This seems like some odd MC client side thing similar to the constant crashing bug that happens on occasion with the fix being the same, but progress has now been made for at least one version of this bug.

In my testing of worlds where the lasso was in the modlist during world gen, I have never once encounted this issue.

Thanks - Valla/Luke

**Comment by LJSkinner** [comment] 2023-09-24 16:30
I'm closing all issues on this repo as I'm going to archive it today. I'm moving on to other projects as I'm just not really interested in continuing it. If you want a good alternative that is regularly updated. Please check out Mob Lassos https://www.curseforge.com/minecraft/mc-mods/mob-lassos by Fuzs.

**Closed as completed by LJSkinner** 2023-09-24 16:30 UTC
Labels: bug, wontfix
